### ISSUE TITLE
Doesn't install using NodeJS 14

### ISSUE THREAD

**Issue by webbedspace** [jakobwesthoff/tosec-tool#12]
I got this error when trying to NPM install:

`Unsupported engine for tosec-tool@2.0.1: wanted: {"node":">= 12 <13"} (current: {"node":"14.17.4","npm":"6.14.14"})`

**Comment by jakobwesthoff** [comment]
I changed the engine definition and added a corresponding `.nvmrc`. However I didn't have time to update any dependencies or address the security issues of them. I hope it should nevertheless work, however use at your own risk.
